(Draft) Add new examples to documentation and categorize pages
stackotter/swift-cross-ui pull request #70
Opened 2023-11-10 05:47 UTC by NinjaCheetah

Added the following examples to `Examples.md` and wrote a short description for each:
- SpitExample
- StressTestExample
- SpreadsheetExample
- ControlsExample

Categorized documentation pages. Currently using the categories `App Structure` (Apple's name for that category), `Views`, `States`, and `Implementation Details`. Descriptions for most of those categories are missing at the moment.

2023-12-09 22:54 UTC, stackotter requested changes
Just a single missing newline, other than that it looks great 👍

2023-12-09 22:54 UTC, stackotter commented on Sources/SwiftCrossUI/SwiftCrossUI.docc/Basic Usage.md
> +For Fedora:
Add a newline before this

2023-12-09 23:07 UTC, Amzd commented on Package.resolved
the Package.swift didn't change, was the Package.resolved change intentional?

2023-12-09 23:10 UTC, stackotter commented on Package.resolved
I reckon that's because they don't have lvgl or qt installed, but yeah I guess the package.resolved should probably be reset to the one from the previous commit so that it's still usefully locking deps. Once the backends are split out into separate packages this shouldn't be an issue anymore

2023-12-09 23:14 UTC, NinjaCheetah commented on Package.resolved
Should the Package.resolved be under version control at all? Most people probably don't have all three backends anyway meaning that the file is going to be regenerated when they go to use it anyway.

2023-12-09 23:24 UTC, Amzd commented on Package.resolved
I guess Package.swift could enforce exact versions to make sure maintainers are using the same versions but usually if you have Package.resolved changes it is a good warning a dependency was updated. It's a trade off with having to be careful when committing.

2023-12-10 07:25 UTC, stackotter approved these changes
lgtm, I'll be addressing the Package.resolved properly soon, so it doesn't really bother me that the Package.resolved was updated by this PR (I've been pretty relaxed about the Package.resolved in the past too)

2023-12-10 08:21 UTC, merged